[package]
name = "yuezhuo"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/hanbings/yuezhuo"
authors = ["hanbings <hanbings@hanbings.io>"]
description = "🐦‍🔥 Yuezhuo - SysY compiler."
keywords = ["compiler"]
license = "MIT"

[[bin]]
name = "compiler"
path = "src/main.rs"

[dependencies]
