mod abi;
mod call;
mod cost;
mod data;
mod division;
mod early_return;
mod layout;
mod local_regs;
mod loop_depths;
mod sig;
mod types;
mod value_uses;

pub(crate) use abi::IrArgLocation;
pub(crate) use call::resolve_call_sig;
pub(crate) use cost::weighted_use_scores;
pub(crate) use data::emit_ir_data_section;
pub(crate) use division::signed_magic_positive;
pub(crate) use early_return::{entry_early_return, EarlyReturnResult, EntryEarlyReturn};
pub(crate) use layout::{ir_align_to, ir_size, IrFuncLayout};
pub(crate) use local_regs::IrLocalRegs;
pub(crate) use loop_depths::{loop_rotated_block_order, natural_loop_depths};
pub(crate) use sig::{IrFuncSig, IrModuleCtx, IrParamSig};
pub(crate) use types::{gep_elem_type, pointee};
pub(crate) use value_uses::ir_value_use_counts;
