name: Sync branch to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push branch to GitLab
        env:
          EDUXIJI_GITLAB_TOKEN: ${{ secrets.EDUXIJI_GITLAB_TOKEN }}
          EDUXIJI_GITLAB_REPO_URL: ${{ secrets.EDUXIJI_GITLAB_REPO_URL }}
        run: |
          git remote add eduxiji \
            "https://oauth2:${EDUXIJI_GITLAB_TOKEN}@${EDUXIJI_GITLAB_REPO_URL}"

          git push -f eduxiji HEAD:${{ github.ref_name }}